---
- name: Generate the Nginx configuration file and restart the service if it has been updated
  template: src=nginx-conf.j2
            dest=/opt/nginx/conf/nginx.conf
  notify: Restart Nginx

- name: Copy Nginx init script and restart the service if it has been updated
  copy: src=nginx-init
        dest=/etc/init.d/nginx
        mode=755
  notify: Restart Nginx

- name: Enable the Nginx init script so the service will start at boot
  command: update-rc.d nginx defaults
           creates=/etc/rc0.d/K20nginx

- name: Set up Nginx vhost directories
  file: path=/etc/nginx/{{ item }}
        state=directory
  with_items:
    - sites-available
    - sites-enabled

- name: Set up log rotation for Nginx & Passenger
  template: src={{ item }}-logrotate.j2
            dest=/etc/logrotate.d/{{ item }}
  with_items:
    - nginx
    - passenger

- name: create logfiles for nginx
  file: path={{helloworld}}/shared/log/{{ item }}
        mode=644
        owner=www-data
        group=www-data
        state=touch
  with_items:
   - nginx-access.log
   - nginx-error.log  
