---
- hosts: nginx-django
  user: root
  sudo: yes

  roles:
    - common
    - deploy-user
    - ssh
    - nginx-passenger
    - django
    - app-helloworld

  vars_prompt:
    upgrade_system: "would you like to run a full system upgrade? (No:yes)"
