---
- name: Add the deploy user
  user: name=deploy
        home=/home/deploy
        shell=/bin/bash
        comment="Deploy User"

- name: Enable sudo access for the deploy user
  user: name=deploy
        groups=sudo
        append=yes

- name: setup authorized keys for deploy user
  authorized_key: user=deploy
                  state=present
                  key="{{ item }}"
  with_file:
    - id_rsa.pub
