---
- name: Install dependencies required for passenger and nginx 
  apt: pkg={{ item }} state=present
  with_items:
    - autoconf
    - build-essential
    - libpcre3-dev
    - libcurl4-openssl-dev
    - libssl-dev
    - zlib1g-dev

- name: Install ruby-{{ ruby_version }}
  apt: pkg=ruby{{ ruby_version }}
       state=present
